//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employ5
    {
        public int empId { get; set; }
        public string name { get; set; }
        public string department { get; set; }
        public string designation { get; set; }
        public Nullable<int> basic { get; set; }
    }
}
